''' Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.  '''


def fiboo(n):
	a,b,isum,i,c,list1=0,1,0,0,0,[]
	for i in range(0,n,1):
		c=a+b
		a=b
		b=c
		
		i+=i
		if(c<4000000 and c%2==0):
			list1.append(c)
			isum+=c
	print 'the sum of the even-valued terms in fibonacci',isum,list1


if __name__=='__main__':
	fiboo(1000)
	
		
